# Generated by Django 3.0.7 on 2021-08-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicno', models.IntegerField()),
                ('tname', models.CharField(max_length=500)),
                ('tref', models.IntegerField()),
                ('surano', models.IntegerField()),
                ('suraname', models.CharField(max_length=100)),
                ('versesno', models.CharField(max_length=200)),
                ('verse', models.CharField(max_length=50000)),
            ],
        ),
    ]
