# Generated by Django 3.0.7 on 2021-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qindex', '0002_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(default='', upload_to='static/pics'),
        ),
    ]
