# Generated by Django 4.1.7 on 2023-03-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qindex', '0003_auto_20210809_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField()),
                ('tname', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='img',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topicno',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tref',
        ),
        migrations.AddField(
            model_name='topic',
            name='t_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qindex.t_list'),
        ),
    ]
