# Generated by Django 4.1.7 on 2023-03-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qindex', '0005_rename_versesno_topic_verseno_alter_topic_t_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('desc', models.TextField(max_length=5000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
