# Generated by Django 3.0.7 on 2023-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qindex', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='bspl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bav', models.CharField(max_length=10000)),
                ('bu', models.CharField(max_length=10000)),
                ('bv', models.CharField(max_length=50000)),
                ('bq', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='btopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_id', models.CharField(max_length=500)),
                ('btname', models.CharField(max_length=500)),
                ('bsurano', models.IntegerField()),
                ('bsuraname', models.CharField(max_length=100)),
                ('bverseno', models.CharField(max_length=200)),
                ('bverse', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='spl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av', models.CharField(max_length=1000)),
                ('eu', models.CharField(max_length=1000)),
                ('v', models.CharField(max_length=50000)),
                ('q', models.CharField(max_length=50000)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='verseno',
            field=models.IntegerField(),
        ),
    ]
